### ISSUE TITLE
s/:smile:/😃 in commit messages

### ISSUE THREAD

**Issue by unhammer** [apertium/phenny#135]
`:smile:` doesn't look good

**Comment by wei2912** [comment]
```
[wei2912@fedora]~/Workspace/goavki/phenny% grep ":smile:" -r .
[wei2912@fedora]~/Workspace/goavki/phenny% 
```

I assume this means the codebase no longer has ":smile:", so I'm closing this issue.

**Comment by scoopgracie** [comment]
No, we _want_ it to contain `:smile:`. It should subst in the emoji.

**Comment by TinoDidriksen** [comment]
Absolutely not? Commit messages should be verbatim, minus newline/whitespace reformatting. If someone physically writes `:smile:` then I don't want the IRC output to change that to `😄`. Especially since this may match in the wrong places and mangle the intent of the message.

Not that IRC replication is an authoritative source, but just the idea of changing commit messages is a no-no to me.

**Comment by unhammer** [comment]
fair enough, could be a commit message like `Undo changing :smile: to 😄` which would quickly get confusing ꞉smile:
