### ISSUE TITLE
general all-purpose flood control

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#252]
Some modules (mailing list, commit messages, etc.) when they get behind might try to post dozens of updates at a time.  These end up more or less flooding a channel.  In these cases, it should post at most three messages: e.g., the earliest update, a message that says "...", and the latest update.

**Comment by jonorthwash** [comment]
Perhaps related to #232 and #159.

**Comment by wei2912** [comment]
Also related to https://github.com/goavki/phenny/issues/236.

**Comment by Androbin** [comment]
This could either be a pure duplicate of #159 or we could intercept all calls to `phenny.msg` and thus have a "general all-purpose flood control". The latter doesn't seem quite right, thou.

Since we don't wanna break things, we could give `phenny.msg` a defaulted parameter to indicate if flood control should be applied or if the calling side knowns what it's doing.

**Comment by wei2912** [comment]
Flood control should be module specific. There are times when information
should not be suppressed by an automatic filter, but rather, left to the
discretion of the module.

A solution to #159 should be adequate to address the issue.

**Comment by Androbin** [comment]
@wei2912 Let's close this as a duplicate then?

**Comment by jonorthwash** [comment]
What issue is this a duplicate of?

**Comment by Androbin** [comment]
See the last two comments.
