### ISSUE TITLE
whois for begiak

### ISSUE THREAD

**Issue by gstark0** [apertium/phenny#362]
How about querying the informations from /whois, from irc.freenode about users? E.g .whois grzegorzs would display informations from what country user is (based on ip adress, as freenode doesn't mask it), and his current time :)

**Comment by Androbin** [comment]
We can't rely on the IP address. The user could be behind a proxy.
Freenode gives me the following "whois" information:
```
== androbin [50932e0e@gateway/web/freenode/ip.80.147.46.14]
==  realname : p50932e0e.dip0.t-ipconnect.de/80.147.46.14
==  channels : #example
==  server   : herbert.freenode.net [Webchat]
==  idle     : 0 days 0 hours 0 minutes 12 seconds [connected: Sun Mar 11 18:55:06 2018]
== End of WHOIS
```
I don't think this would be that useful.

**Comment by Androbin** [comment]
The RFC standard for IRC defines a USERHOST message:
   The USERHOST command takes a list of up to 5 nicknames, each
   separated by a space character and returns a list of information
   about each nickname that it found.  The returned list has each reply
   separated by a space.

**Comment by scoopgracie** [comment]
why is this needed if we can already do /whois someone?

**Comment by wei2912** [comment]
I don't think it's useful as a replacement for `whois`, but it could help in GCI by providing a directory of mentors and useful information about them.

**Comment by scoopgracie** [comment]
Oh, yeah, that is a good idea. Maybe show data like
    <nick> - <username on GitHub>
    <nick> is a GCI mentor. (S)he is listed as <gci-name> on GCI tasks.

**Comment by wei2912** [comment]
See my previous comments on the GCI page. I also made a few modifications to break the task up into two parts.

> Anyways, this function is intended solely for developers/mentors and not for GCI students, as we don't want your personal data to be released.
>
> I'd like the following functionality for a `.whois` command:
>
> Parameters:
> 1. IRC nick(s)/real name (fuzzy search) (Part 1)/GitHub username/wiki username (Part 2)
>
> Line 1:
> 1. GCI/GSOC info - an indication of whether the person is an "org admin" or "mentor"; not sure what's the equivalent for GSOC... (Part 2)
> 2. Timezones - an officially provided timezone of the mentor (Part 1), and if possible some stats on when the mentor was most often seen across all of his/her nicks (Part 3)
> 3. Last seen - try to integrate with the last seen, so that the function provides info for the last seen of each of the nicks (Part 3)
>
> Line 2:
> 4. Profile link - let the user specify their own wiki/GitHub/profile page (Part 2)

**Comment by wei2912** [comment]
@scoopgracie For Part 1, since you've already done up the part on the official timezone, I'll just need you to do the following:
1. Take out the `.alias` code from the `.tell` module and put it into its own module.
2. For the searching of IRC nick/real name, I'd want the `.whoissearch` command to be removed so that we can search for nicks directly through `.whois`. Just have begiak return the top result (so that we don't spam the channel with search results), similar to what is done for `.awik`. If we find that it is necessary to return more than just the top search result, we can always integrate this with the `.more` module.
(It doesn't matter if the GitHub/wiki nick thing gets broken due to these changes - so long as you fulfil the criteria for IRC nick(s)/real name search and timezone, I'll accept it as a task.)
